function [out]=string2varname(in,message);


out=regexprep(in,'[^a-zA-Z_0-9]','');

% out=in;
% replace={...
%     ' ',    '';...
%     '(',    '';...
%     ')',    '';...
%     '[',    '';...
%     ']',    '';...
%     '{',    '';...
%     '}',    '';...
%     '-',    '';...
%     '/',    '';...
%     '\',    '';...
%     '^',    '';...
%     };
% 
% for m=1:size(replace,1)
%     out = regexprep(out,replace{m,1},replace{m,2});
% end

% check if every entry has unique name
if exist('message','var')==0; message=1; end;

if message==1 && size(unique(out),1)<size(in,1);
    h = msgbox('string2varname not unique');
end